# Generated by Django 4.2 on 2023-08-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bromine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybloginfo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
