# Generated by Django 4.2 on 2023-08-08 02:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bromine', '0002_mybloginfo_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybloginfo',
            name='Likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mybloginfo',
            name='category',
            field=models.CharField(blank=True, default='coding', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mybloginfo',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
