# Generated by Django 4.2 on 2023-08-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bromine', '0003_mybloginfo_likes_mybloginfo_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybloginfo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
