# Generated by Django 4.2 on 2023-08-10 21:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bromine', '0010_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybloginfo',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
